[faucet]
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-store', 1)) % 2**16
endpoint = { protocol = "http", host = "localhost", port = 8080 }
rpc_endpoint = { protocol = "http", host = "localhost", port = 57291 }
database_filepath = "miden-faucet.sqlite3"
